language: cpp
sudo: required
dist: trusty
matrix:
  env:
    - TARGET=app.elf
    - TARGET=test.elf
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: PLATFORM=device
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env: PLATFORM=simulator

os: linux
before_install:
- sudo apt-add-repository -y 'deb http://archive.ubuntu.com/ubuntu trusty main universe multiverse restricted'
- sudo apt-get -qq update
- sudo apt-get -y install gcc-arm-none-eabi
- if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.6" CC="clang-3.6"; fi
- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
script:
- make clean && make TARGET
