language: cpp
sudo: required
compiler:
- clang
- gcc
os:
- linux
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y libpng-dev
- ls /usr/include/libpng12
- ls /usr/lib/x86_64-linux-gnu
script: make app.elf && make test.elf
